### PR TITLE
Add support for JetBrains IDE built-in terminal

### PR DESCRIPTION
**Pull request by Asvarox**
Hello, great plugin!

I noticed it didn't initialise in JetBrains' (eg. IntelliJ IDEA) built-in terminal and found a quick-fix for it, so I thought I'd share

### CODE REVIEW

**Comment by marzocchi** [comment]
hey @Asvarox, thanks! But then, does it work? eg. there's no code to detect JetBrains' terminal foreground state for example.

**Comment by marzocchi** [comment]
ah, checked... so with this change we get a notification after every command regardless of the JetBrains's foreground state, but based on Apple Terminal... that's because the code for Apple Terminal is triggered as it matches this condition (`TERM_PROGRAM` is not set but `TERM_SESSION_ID` is)

https://github.com/marzocchi/zsh-notify/blob/eb389765cb1bd3358e88ac31939ef2edfd539825/applescript/functions#L31

do you know if JetBrains's terminal supports any form of scripting that could be used to query it's state? ideally the notifications from this plugin should appear _only_ when the user is **not** looking at the terminal.

**Comment by Asvarox** [comment]
Hey, yes, it does work (at least on MacOS), but good point - it displays the notification regardless of the state. I'll see if that can be fixed over the weekend

**Comment by marzocchi** [comment]
sure, thanks!

**Comment by Asvarox** [comment]
I looked into it, and it doesn't seem trivial/possible. All I could figure out was to show the notification when entire IDE is in the background, but thought it'd do more harm than good - I'm not using the terminal often myself, but I'd expect the notification to show when it's minimised within the IDE. This could probably be done though a plugin, though I think it's (way) out of scope of this project :) .

My colleagues still find it useful though, so I'm thinking it could be an opt-in feature?

**Pull request closed without merging**
