### PR TITLE
Fix wmctrl window argument

### PR DESCRIPTION
**Pull request by zpdcodes**

### CODE REVIEW

**Comment by hoshsadiq** [comment]
This PR temporary broke my setup. For some reason it would switch focus to a different terminal window when a command failed. In my case I am running 2 x Alacritty + 2 x tmux. Not sure what was wrong but I had to kill tmux server and restart it before it worked properly again.

So for anyone else coming here in the future, run the following and restart your terminals:

```
tmux kill-server
```

**Comment by hoshsadiq** [comment]
Actually that didn't fix the issue. For now I've disabled the urgency hint:

```
zstyle ':notify:*' disable-urgent true
```

**Comment by marzocchi** [comment]
thanks for your feedback @hoshsadiq, any hint on what might be the cause of the issue?

**Comment by hoshsadiq** [comment]
When I discovered this issue, I had a quick look but didn't really fully dedicate time on it as I don't use the urgency feature. Investigated a little bit just now, and realised that the issue might be in the function `store-window-id` (there's a comment that might be related).

PS: I don't know if it's on purpose, but the issues tab is disabled.

**Pull request merged**
