### PR TITLE
Note macOS specific setup steps

### PR DESCRIPTION
**Pull request by imann24**
_Thanks so much for creating this package! So useful and intuitive._

### Change(s)
1. Add explicit instructions on how to install `terminal-notifier`

### CODE REVIEW

**Comment by marzocchi** [comment]
hi @imann24 and thanks! 

while it's probably not as-clear-as-it-could-be that this package requires `terminal-notifier` on mac and `notify-send` on linux, as a macports user these look more like homebrew-specific installation steps ;) 

jokes aside, I prefer to keep first and foremost installation instructions that are more universal (a mac ships with git, zsh and safari to go to terminal-notifier's repo and download a release), while instructions for some third party package manager are just a nice to have that can go at the bottom (with the instructions for antigen, etc.).

**Comment by imann24** [comment]
Appreciate your notes. Would hate to leave the `MacPorts` users in the cold 😅 

As an alternate suggestion, I wonder whether moving the prereqs under a **Setup** header makes them more explicit? 

Entirely agree that anyone with Mac's default tools should be able to figure out a way to snag `terminal-notifier` without much trouble, if they visit its repo.

**Comment by imann24** [comment]
Side-note, this was my first time encountering reference links in markdown. Appreciate the new learning!

**Comment by marzocchi** [comment]
_as a macports user_, thanks ;)

**Comment by imann24** [comment]
Thank you! Greatly appreciate you putting this package out there

**Pull request merged**
