### PR TITLE
Added window focusing for Linux

### PR DESCRIPTION
**Pull request by PlasmaPower**

### CODE REVIEW

**Comment by marzocchi** [comment]
thank you @PlasmaPower!

is this `wmctrl` command a standard one? if not, could you please add it to the list of requirements in the README?

**Comment by PlasmaPower** [comment]
I don't think it is very standard, however it is in most repositories. I'll add it to the README in a new PR.

**Comment by marzocchi** [comment]
thank you!

**Comment by PlasmaPower** [comment]
No problem.

**Pull request merged**
