### PR TITLE
Add linux support

### PR DESCRIPTION
**Pull request by thatsmydoing**

### CODE REVIEW

**Comment by marzocchi** [comment]
Hi @thatsmydoing and thank you very much for your contribution! I rarely use Linux on the desktop so I never had the chance to add support for it; plus I didn't know about xdotool.

**Comment by thatsmydoing** [comment]
I've added the additional check, it's actually the only case left, but yeah, it's probably easier to understand and extend with the additional condition.

I just recently shifted to linux since using OSX, and I really liked this plugin, so I had to add support in :)

**Comment by marzocchi** [comment]
Hey, thank you @thatsmydoing! Makes me happy that this little silly project is making other people happy too!  :+1:

I had the chance to try it under Ubuntu, notification for failed commands work as expected (I get the notification every time), but when a command terminates successfully the notification should be posted only if the terminal is not activate (or the terminal tab is not active); do you think it's possible to do the same with xdotool?

**Comment by thatsmydoing** [comment]
Ah, I didn't test out tabs. It should work for different terminal windows though.

That's probably not as easy to detect since you'd have to have logic for each different terminal emulator. I'm not even sure it's possible for most terminal emulators.

**Comment by marzocchi** [comment]
Uh, ignore my previous message, I tested it the wrong way: I opened a `gnome-terminal` window with bash, then launched `zsh --login`, so `ACTIVEPID` was always different to `$PPID_FIRST`.

**Pull request merged**
