### PR TITLE
ignore editors and pagers command

### PR DESCRIPTION
**Pull request by xight**

### CODE REVIEW

**Comment by marzocchi** [comment]
Thank you for your contribution @xight!

However it turns out that this variable is not used anymore.

```
$ grep last_command_name -r .
./notify.plugin.zsh:    last_command_name=${1[(wr)^(*=*|sudo|ssh|-*)]}
```

I also checked older commits, and it seems like I actually never used it?!

That line will assign to `last_command_name` the first word from `$1`, unless it's one of the listed program names, in which case it will take the next. If I recall correctly I used it for something related to the notification, so it might not be related to what you want to do.

From _what_ would you like to filter out editors and pagers?

**Comment by xight** [comment]
Thank you for your reply!

I think that people want to notify when heavy task finished. e.g. deployment, testing, and so on.

zsh-notify notify me when I finish editting, but I don't want to.
because I know that I quitted editor.

this code work for me. (ignore editors and pagers)
but it is based on master branch.

Should I have fixed base on develop branch...?

**Comment by marzocchi** [comment]
> zsh-notify notify me when I finish editting, but I don't want to.

But this shouldn't happen, at least most of the time: the notification should be issued only when the terminal window is in background, which is unlikely to be true when editing (eg.: unless you are extra quick in typing `:q` in vim and hiding the terminal).

Maybe there's something broken elsewhere?! What system and terminal application are you using?

**Comment by xight** [comment]
> But this shouldn't happen, at least most of the time: the notification should be issued only when the terminal window is in background, which is unlikely to be true when editing (eg.: unless you are extra quick in typing :q in vim and hiding the terminal).

I try to reproduce but can't...


> Maybe there's something broken elsewhere?! What system and terminal application are you using?

I use iTerm2 Build 3.0.10 + zsh5.2 + prezto

I'll check more carefully, and think about what I want to do again.

Thanks.

**Pull request closed without merging**
